### ISSUE TITLE
SureFire Plugin - Unit Testing and Integrated Testing Error

### ISSUE THREAD

**Issue by maypst** [kaungmyat128/devops_coursework#41]
**Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin :2.19.1:test (default-test) in Unit Testing & Integrated Testing**

**Steps to Reproduce the behavior**
 - [List the specific steps to reproduce the bug. Be as detailed as possible, including any relevant data or inputs used.]
 - [If applicable, provide any additional steps or context that may help in reproducing the issue.]
Steps should be reported as following example:
1. Add dependencies and plugin in pom.xml
2. Change workflow in main.yml
3. Implement 'IntegratedTest' and 'UnitTest' Files in Test Folder
4. Run Maven Packages and See Error
5. Commit to GitHub and See SureFire Plugin Error

**Expected Behavior**
The workflow should run without error and pass IntegratedTest and UnitTest.

**Actual Behavior**
In Unit Testing Section : Error:  Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test)
In Integrated Testing Section : Error:  Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) 

**Screenshots/Recordings**
Detail error can be seen in Commit ** 3aab1fd unit-testing **

**Desktop**
 - OS: Windows
 - Browser Chrome
 - Version/Commit: 3aab1fd unit-testing branch

**Additional Information**
-

**Comment by Kaung-K-H** [comment]
The location of error is in main.yml file.
Instead of given the actual file name (UnitTest or IntegratedTest), the file names were Unit_test and IntegratedTesting.
