### ISSUE TITLE
4 Errors found out of 15 Total Tests

### ISSUE THREAD

**Issue by maypst** [kaungmyat128/devops_coursework#43]
**4 Errors found out of 15 Total Tests**

**Steps to Reproduce the behavior**
Steps should be reported as following example:
1. Wrote tests in UnitTesting File
2. Configured main.yml
3. Added Dependencies in pom.xml
4. See Test Errors when workflow runs

**Expected Behavior**
All tests should passed successfully in both local machine and GitHub Workflow.

**Actual Behavior**
Error:  Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project devops: There are test failures.
Tests run: 15, Failures: 0, Errors: 4, Skipped: 0

**Screenshots/Recordings**
Detail error can be seen in 4c940a5 unit-testing.

**Desktop**
 - OS: Windows
 - Browser Chrome
 - Version/Commit: 4c940a5 unit-testing

**Additional Information**
-

**Comment by Kaung-K-H** [comment]
The error occurs due to some methods not having Exception handling methods. Exceptions are added are not properly working as of now.

**Comment by maypst** [comment]
Errors occur when testing displayCapitalNull(), displayCapitalsTestContainsNull(), displaySummaryNull() and displaySummaryTestContainsNull(). The reason of error is NullPointer Error. Exception handling 'catch' statements written in display method of Capital and Summary Reports.
